name: PluginTemplate
version: '1.0'
main: dev.draconicdevelopment.pluginTemplate.PluginTemplate
api-version: '1.21'
authors: [ Mike31232 ]
description: Development plugin
commands:
  ExampleCommand:
    permission: PluginTemplate.Command.Example
    description: Main plugin command for the template
    aliases:
      - example
